/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booklist;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Van
 */
public class BookViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form BookListFrame
     */
    public BookViewFrame() {
        initComponents();
    }

    // method to conduct binary search
    public int binarySearch(Integer[] a, int key) {
        int start = 0;
        int end = a.length - 1;
        int searchedValue = key;

        for (int i = 0; i <= a.length; i++) {
            int mid = (start + end) / 2;

            if (searchedValue == a[mid]) {
                return mid;
            }

            if (searchedValue < a[mid]) {
                end = mid - 1;
            } else {
                start = mid + 1;
            }
        }
        return -1;
    }
    
    // method to conduct linear search
    public static int linearSearch(Integer[] arr, int key){    
        for(int i=0;i<arr.length;i++){    
            if(arr[i] == key){    
                return i;    
            }    
        }    
        return -1;    
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBookViewInfo1 = new javax.swing.JLabel();
        lblBookViewInfo2 = new javax.swing.JLabel();
        lblEnterReferenceNum = new javax.swing.JLabel();
        txtUserReferenceNum = new javax.swing.JTextField();
        btnFindBook = new javax.swing.JButton();
        lblLinearSearch = new javax.swing.JLabel();
        lblBinarySearch = new javax.swing.JLabel();
        txtBookLinearSearch = new javax.swing.JTextField();
        txtBookBinarySearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(100, 240, 90));
        lblTitle.setText("Children's Classics");

        lblBookViewInfo1.setText("This program will find the title of a book according to the library reference number.");

        lblBookViewInfo2.setText("The program will use a Binary Search and a Linear Search.");

        lblEnterReferenceNum.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblEnterReferenceNum.setText("Enter The Reference #:");

        btnFindBook.setText("Find It!");
        btnFindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBookActionPerformed(evt);
            }
        });

        lblLinearSearch.setText("Linear Search:");

        lblBinarySearch.setText("Binary Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBookViewInfo2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterReferenceNum)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserReferenceNum)))
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(btnFindBook))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblBookViewInfo1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLinearSearch)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtBookLinearSearch))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblBinarySearch)
                            .addGap(31, 31, 31)
                            .addComponent(txtBookBinarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblTitle)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblBookViewInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBookViewInfo2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterReferenceNum)
                    .addComponent(txtUserReferenceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnFindBook)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinearSearch)
                    .addComponent(txtBookLinearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinarySearch)
                    .addComponent(txtBookBinarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBookActionPerformed


        
    // Read the file and convert into arraylist
    // Open the file
    FileReader fr = null;
    BufferedReader br = null;
    try {
      fr = new FileReader("Booklist.txt");
      br = new BufferedReader(fr);
      int lineCounter = 0;
      String bookentry = "";
      List<Integer> bookindex=new ArrayList<>();
      //String[] bookline; 
      ArrayList<String> booklist = new ArrayList<String>();
      String line;
      while ((line = br.readLine()) != null) {
            lineCounter++; 
            if ((lineCounter % 2) == 0) {
                bookentry += line;
                booklist.add(bookentry);
                bookentry="";
            } 
            else
            {
                bookentry = line + ", ";
                bookindex.add(Integer.parseInt(line));
            }
              // process the line
              // Add to search array and 
          System.out.println(line);
        }
      
      //System.out.println(booklist);
      //System.out.println(bookindex);
      Integer[] bookarr = new Integer[bookindex.size()];
      bookarr = bookindex.toArray(bookarr);
      // displays message if the reference # doesn't correspond with a book title
      if (linearSearch(bookarr, Integer.parseInt(txtUserReferenceNum.getText())) == -1) {
          txtBookLinearSearch.setText("Book is not on the table, table!!");
      }
      else {
          txtBookLinearSearch.setText((booklist.get(linearSearch(bookarr, Integer.parseInt(txtUserReferenceNum.getText()))).split(",")[1].trim()));
      }
      // displays message if the reference # doesn't correspond with a book title
      if (binarySearch(bookarr, Integer.parseInt(txtUserReferenceNum.getText())) == -1) {
        txtBookBinarySearch.setText("Book is not on the table, table!!");  
      }
      else {
        txtBookBinarySearch.setText((booklist.get(binarySearch(bookarr, Integer.parseInt(txtUserReferenceNum.getText()))).split(",")[1].trim()));
      }

    } catch (FileNotFoundException e) {
        System.err.println("Can not find specified file!");
    } catch (IOException e) {
     System.err.println("Can not read from file!");
    } finally {
       if (br != null) try { br.close(); } catch (IOException e) { /* ensure close */ }
       if (fr != null) try { fr.close(); } catch (IOException e) { /* ensure close */ }
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindBook;
    private javax.swing.JLabel lblBinarySearch;
    private javax.swing.JLabel lblBookViewInfo1;
    private javax.swing.JLabel lblBookViewInfo2;
    private javax.swing.JLabel lblEnterReferenceNum;
    private javax.swing.JLabel lblLinearSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBookBinarySearch;
    private javax.swing.JTextField txtBookLinearSearch;
    private javax.swing.JTextField txtUserReferenceNum;
    // End of variables declaration//GEN-END:variables
}
