/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Johnny
 * @author Peter
 */
public class FinalProject extends javax.swing.JFrame {

    //Make rock paper scissors
    RockPaperScissors rps = new RockPaperScissors();

    /**
     * Creates new form FinalProject
     */
    public FinalProject() {
        initComponents();
        setResizable(false); // user cannot resize the game, to break it
        textArea.setEditable(false); // made it so user cannot edit the text boxes
        textPlayerScore.setEditable(false);
        textComputerScore.setEditable(false);
        setLocationRelativeTo(null); // set location of gui location to the center of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        exitBt = new javax.swing.JButton();
        rockRb = new javax.swing.JRadioButton();
        paperRb = new javax.swing.JRadioButton();
        scissorRb = new javax.swing.JRadioButton();
        playerImage = new javax.swing.JLabel();
        playerBt = new javax.swing.JButton();
        computerImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        textPlayerScore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textComputerScore = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setText("Rock, Paper, Scissors");

        exitBt.setText("Exit");
        exitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtActionPerformed(evt);
            }
        });

        buttonGroup1.add(rockRb);
        rockRb.setText("Rock");
        rockRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(paperRb);
        paperRb.setText("Paper");
        paperRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(scissorRb);
        scissorRb.setText("Scissors");
        scissorRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorRbActionPerformed(evt);
            }
        });

        playerImage.setText("...");

        playerBt.setText("Play");
        playerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerBtActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        textPlayerScore.setText("Player Score");

        jLabel2.setText("Player Score");

        textComputerScore.setText("Computer Score");

        jLabel4.setText("Computer Score");

        jLabel5.setText("Computer Choice");

        jLabel6.setText("Player Choice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textComputerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playerBt)
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paperRb)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scissorRb)
                                    .addComponent(rockRb))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(computerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rockRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paperRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scissorRb))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(computerImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(playerBt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textComputerScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(exitBt)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerBtActionPerformed

        if (!rockRb.isSelected() && !paperRb.isSelected() && !scissorRb.isSelected()) { // User has to select either ROCK, PAPER, OR SCISSORS to start the game
            JOptionPane.showMessageDialog(null, "You did not select a choice (Rock, Paper, or Scissors)!");
        } else {
            if (rockRb.isSelected()) {
                rps.playerPlay("rock");
            } else if (paperRb.isSelected()) {
                rps.playerPlay("paper");
            } else if (scissorRb.isSelected()) {
                rps.playerPlay("scissors");
            }
            //Computer Move
            int computerMove = (int) (Math.random() * 3);
            if (computerMove == 0) {
                rps.computerPlay("rock");
                ImageIcon icon = new ImageIcon("rock.jpg");
                computerImage.setIcon(icon);
            } else if (computerMove == 1) {
                rps.computerPlay("paper");
                ImageIcon icon = new ImageIcon("paper.jpg");
                computerImage.setIcon(icon);
            } else if (computerMove == 2) {
                rps.computerPlay("scissors");
                ImageIcon icon = new ImageIcon("scissors.jpg");
                computerImage.setIcon(icon);
            }
            //Find winner
            String winner = rps.checkforwinner();
            textArea.setText(winner);
            textPlayerScore.setText(rps.getPlayerScore() + "");
            textComputerScore.setText(rps.getComputerScore() + "");
        }


    }//GEN-LAST:event_playerBtActionPerformed

    private void rockRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockRbActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("rock.jpg");
        playerImage.setIcon(icon);
    }//GEN-LAST:event_rockRbActionPerformed

    private void paperRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperRbActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("paper.jpg");
        playerImage.setIcon(icon);
    }//GEN-LAST:event_paperRbActionPerformed

    private void scissorRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorRbActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("scissors.jpg");
        playerImage.setIcon(icon);
    }//GEN-LAST:event_scissorRbActionPerformed

    private void exitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtActionPerformed
        System.exit(0); // exit the program
    }//GEN-LAST:event_exitBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel computerImage;
    private javax.swing.JButton exitBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton paperRb;
    private javax.swing.JButton playerBt;
    private javax.swing.JLabel playerImage;
    private javax.swing.JRadioButton rockRb;
    private javax.swing.JRadioButton scissorRb;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textComputerScore;
    private javax.swing.JTextField textPlayerScore;
    // End of variables declaration//GEN-END:variables
}
