/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fractionreducer;

/**
 *
 * @author Van
 */
public class FractionReducerFrame extends javax.swing.JFrame {

    /**
     * Creates new form FractionReducerFrame
     */
    public FractionReducerFrame() {
        initComponents();
    }
  
    class Fraction {
 
   int numerator;
   int denominator;
 
   Fraction(int n, int d) {
      numerator = n;
      denominator = d;
      reduce();
   }
 
   Fraction(double d) {
      int i = ("" + d).split("\\.")[1].length();
		denominator = (int) Math.pow(10, i); 
		numerator = (int) (d * denominator); 
      reduce();
   }
 
   private void reduce() {
      // find the larger of the numerator and denominator
      int n = numerator, d = denominator, largest;
      if (numerator < 0) {
         n = -numerator;
      }
      if (n > d) {
         largest = n;
      } else {
         largest = d;
      }
 
      // find the largest number that divide the numerator and
      // denominator evenly
      int gcd = 0;
      for (int i = largest; i >= 2; i--) {
         if (numerator % i == 0 && denominator % i == 0) {
            gcd = i;
            break;
         }
      }
 
      // divides the largest common denominator out of numerator and denominator
      if (gcd != 0) {
         numerator /= gcd;
         denominator /= gcd;
      }
   }
 
   public String toString() {
      return numerator + "/" + denominator;
   }
}
  
    static int res = 1;
    public static int calculateLCM(int num1, int num2) {
        if (res % num1 == 0 && res % num2 == 0)
          return res;

        res++;
        calculateLCM(num1, num2);

        return res;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFractionInfo = new javax.swing.JLabel();
        lblEnterNumerator = new javax.swing.JLabel();
        lblEnterDenominator = new javax.swing.JLabel();
        txtUserNumerator = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutputReducedFraction = new javax.swing.JTextArea();
        txtUserDenominator = new javax.swing.JTextField();
        btnReduceFractionToLowest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTitle.setText("Fraction Reducer");

        lblFractionInfo.setText("This program will reduce a fraction to lowest terms.");

        lblEnterNumerator.setText("Enter the Numerator:");

        lblEnterDenominator.setText("Enter the Denominator:");

        txtOutputReducedFraction.setColumns(20);
        txtOutputReducedFraction.setRows(5);
        jScrollPane1.setViewportView(txtOutputReducedFraction);

        btnReduceFractionToLowest.setText("Reduce Fraction to Lowest Terms");
        btnReduceFractionToLowest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReduceFractionToLowestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterDenominator)
                            .addComponent(lblEnterNumerator))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserNumerator, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserDenominator, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblFractionInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnReduceFractionToLowest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblTitle)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addComponent(lblFractionInfo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterNumerator)
                    .addComponent(txtUserNumerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterDenominator)
                    .addComponent(txtUserDenominator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnReduceFractionToLowest)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReduceFractionToLowestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReduceFractionToLowestActionPerformed

        int Numerator =  Integer.parseInt(txtUserNumerator.getText());
        int Denominator =  Integer.parseInt(txtUserDenominator.getText());
        Fraction f1 = new Fraction(Numerator, Denominator);
        String result = "";
        result = f1.toString();
        txtOutputReducedFraction.setText(result);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReduceFractionToLowestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractionReducerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractionReducerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractionReducerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractionReducerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractionReducerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReduceFractionToLowest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterDenominator;
    private javax.swing.JLabel lblEnterNumerator;
    private javax.swing.JLabel lblFractionInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtOutputReducedFraction;
    private javax.swing.JTextField txtUserDenominator;
    private javax.swing.JTextField txtUserNumerator;
    // End of variables declaration//GEN-END:variables
}
