/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mathmethods;
import java.util.*;

/**
 *
 * @author Van
 */
public class MathMethodsFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form mathMethodsFRame
     */
    public MathMethodsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserFirstNum = new javax.swing.JTextField();
        txtUserSecondNum = new javax.swing.JTextField();
        btnPower = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        btnDivideRound = new javax.swing.JButton();
        btnMaxNum = new javax.swing.JButton();
        btnMinNum = new javax.swing.JButton();
        txtUserResult = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblFirstNum = new javax.swing.JLabel();
        lblSecondNum = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPower.setText("Power");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        btnRandom.setText("Random Number");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnDivideRound.setText("Divide (Rounds To Nearest Whole Number)");
        btnDivideRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideRoundActionPerformed(evt);
            }
        });

        btnMaxNum.setText("Maximum");
        btnMaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxNumActionPerformed(evt);
            }
        });

        btnMinNum.setText("Minimum");
        btnMinNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinNumActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(80, 200, 100));
        lblTitle.setText("Math Methods");

        lblFirstNum.setText("First Number");

        lblSecondNum.setText("Second Number");

        lblResult.setText("Result");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblFirstNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSecondNum)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnMaxNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnMinNum)
                .addGap(17, 17, 17)
                .addComponent(btnRandom)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUserFirstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(txtUserSecondNum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnDivideRound, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(txtUserResult, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblResult)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnExit)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstNum)
                    .addComponent(lblSecondNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserFirstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserSecondNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPower)
                    .addComponent(btnRandom)
                    .addComponent(btnMaxNum)
                    .addComponent(btnMinNum))
                .addGap(18, 18, 18)
                .addComponent(btnDivideRound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserResult, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// function used to store user input in variables, and then check if they're valid doubles
private void VerifyIfDouble(){
       String FirstNum;
       String SecondNum; 
    
       FirstNum = txtUserFirstNum.getText();
       SecondNum = txtUserSecondNum.getText();
        
        try {
            double FirstNumCheck = Double.parseDouble(FirstNum);
        }
        catch(NumberFormatException ex) {
            txtUserResult.setText(FirstNum +" isn't a valid number. Try again!");
        }
        try {
            double SecondNumCheck = Double.parseDouble(SecondNum);
        }
        catch(NumberFormatException ex) {
            txtUserResult.setText(SecondNum +" isn't a valid number. Try again!");
        }
    }

// function to turn valid user input into doubles, and then store them in an array for easy access
public ArrayList<Double> turnUserInputToDouble(){
    double FirstNum;
    double SecondNum; 
    
    FirstNum = Double.parseDouble(txtUserFirstNum.getText());
    SecondNum = Double.parseDouble(txtUserSecondNum.getText());
    
    ArrayList<Double> list = new ArrayList<Double>();
    list.add(FirstNum);
    list.add(SecondNum);
    
    return (list);
}

    private void btnMaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxNumActionPerformed
       // calling on the fuctions i previously made
       VerifyIfDouble();    
       // storing the doubles returned from the function in a local array
       ArrayList<Double> UserNumList = turnUserInputToDouble();
       
       // getting the max from the two inputed numbers using Math.max()    
       double maxResult = Math.max(UserNumList.get(0), UserNumList.get(1));
       
       // result is ouputed
       txtUserResult.setText(String.valueOf(maxResult));
       
    }//GEN-LAST:event_btnMaxNumActionPerformed

    private void btnMinNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinNumActionPerformed

       VerifyIfDouble();
       ArrayList<Double> UserNumList = turnUserInputToDouble();

       // getting the min from the two inputed numbers using Math.min()
       double minResult = Math.min(UserNumList.get(0), UserNumList.get(1));
       
       txtUserResult.setText(String.valueOf(minResult));
       
    }//GEN-LAST:event_btnMinNumActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed

       VerifyIfDouble();
       ArrayList<Double> UserNumList = turnUserInputToDouble();

       // getting the result of the first number inputed to the power of the second using Math.pow()
       double powResult = Math.pow(UserNumList.get(0), UserNumList.get(1));
       
       txtUserResult.setText(String.valueOf(powResult));    
       
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnDivideRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideRoundActionPerformed

       VerifyIfDouble();
       ArrayList<Double> UserNumList = turnUserInputToDouble();

       // dividing both numbers then rounding the result using Math.round()
       double divideResult = Math.round(UserNumList.get(0)/UserNumList.get(1));
       
       txtUserResult.setText(String.valueOf(divideResult));
       
    }//GEN-LAST:event_btnDivideRoundActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed

       VerifyIfDouble();
       ArrayList<Double> UserNumList = turnUserInputToDouble();

       // creates a range between the two nunmbers inputed (while still including those numbers) and produces a random number between the set range using Math.random()
       double randomResult = UserNumList.get(0) + (int)(Math.random()* ((UserNumList.get(1) - (UserNumList.get(0)) + 1)));
       
       txtUserResult.setText(String.valueOf(randomResult));
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

         // exits program upon clicking the exit button
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MathMethodsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivideRound;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMaxNum;
    private javax.swing.JButton btnMinNum;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRandom;
    private javax.swing.JLabel lblFirstNum;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSecondNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtUserFirstNum;
    private javax.swing.JTextField txtUserResult;
    private javax.swing.JTextField txtUserSecondNum;
    // End of variables declaration//GEN-END:variables
}
