/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;

import com.mycompany.finalproject.splashscreen.Draw;
import com.mycompany.finalproject.splashscreen.GameOver;
import com.mycompany.finalproject.splashscreen.Victory;
import javax.swing.ImageIcon;

/**
 *
 * @author johnn
 */
public class Challenger extends javax.swing.JFrame {
    int numberOfRounds;
    int curRound = 0;
    //Make rock paper scissors
    RockPaperScissors rps;

    /**
     * Creates new form Challenger
     * @param numberOfRounds
     */
    public Challenger(int numberOfRounds) {
        initComponents();
        
        this.numberOfRounds = numberOfRounds;
        this.rps = new RockPaperScissors();
        
        setLocationRelativeTo(null);
        setResizable(false);
        
        updateControls();
        ImageIcon a = new ImageIcon("challenger.png");
        challenger.setIcon(a);
    }
    
    public void updateControls() {
        int player = rps.getPlayerScore();
        int computer = rps.getComputerScore();
        
        lblRound.setText("Next round: " + (curRound + 1));
        lblPlayerScore.setText("Your score: " + player);
        lblChallengerScore.setText("Challenger's score: " + computer);
        
        if (curRound == numberOfRounds) {
            if (player > computer) {
                new Victory(this, player, computer).setVisible(true);
            }
            else if (computer > player) {
                new GameOver(this, player, computer).setVisible(true);
            }
            else {
                new Draw(this, player, computer).setVisible(true);
            }
        }
        else {
            setVisible(true);
        }
        
        curRound++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRock = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnScissor = new javax.swing.JButton();
        lblRound = new javax.swing.JLabel();
        lblPlayerScore = new javax.swing.JLabel();
        lblChallengerScore = new javax.swing.JLabel();
        challenger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("A challenger approaches!");

        btnRock.setText("ROCK");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        btnPaper.setText("PAPER");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        btnScissor.setText("SCISSORS");
        btnScissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorActionPerformed(evt);
            }
        });

        lblRound.setText("Current Round:");

        lblPlayerScore.setText("Your score:");

        lblChallengerScore.setText("Challenger's score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRound)
                            .addComponent(lblPlayerScore)
                            .addComponent(lblChallengerScore))
                        .addGap(22, 22, 22)
                        .addComponent(challenger, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRock, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnScissor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel1))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblRound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChallengerScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(challenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRock)
                .addGap(18, 18, 18)
                .addComponent(btnPaper)
                .addGap(18, 18, 18)
                .addComponent(btnScissor)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        setVisible(false);
        new FinalProject(rps, 0, curRound, numberOfRounds, this).setVisible(true);
    }//GEN-LAST:event_btnRockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        setVisible(false);
        new FinalProject(rps, 1, curRound, numberOfRounds, this).setVisible(true);
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorActionPerformed
        setVisible(false);
        new FinalProject(rps, 2, curRound, numberOfRounds, this).setVisible(true);
    }//GEN-LAST:event_btnScissorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissor;
    private javax.swing.JLabel challenger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChallengerScore;
    private javax.swing.JLabel lblPlayerScore;
    private javax.swing.JLabel lblRound;
    // End of variables declaration//GEN-END:variables
}
